spring:
  application:
    name: zero-code
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zero_code
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
      ttl: 3600
      password: 123456
mybatis-flex:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启日志
server:
  port: 8111
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.zerocode.controller