spring:
  application:
    name: zero-code
  profiles:
    active: local
server:
  port: 8111
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.zerocode.controller